---
development:
  cloud_name: dpfo5wjwg
  api_key: '339187993436752'
  api_secret: Q09ZOTC-hfpQxJzaD1SirnHyQBw
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dpfo5wjwg
  api_key: '339187993436752'
  api_secret: Q09ZOTC-hfpQxJzaD1SirnHyQBw
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dpfo5wjwg
  api_key: '339187993436752'
  api_secret: Q09ZOTC-hfpQxJzaD1SirnHyQBw
  enhance_image_tag: true
  static_image_support: false
